name: Java CI without Maven or JDK setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install OpenJDK 11
      run: sudo apt-get update && sudo apt-get install -y openjdk-11-jdk

    - name: Check Java version
      run: java -version

    - name: Check javac version
      run: javac -version

    - name: Compile Java code
      run: javac -d out $(find . -name "*.java")

    - name: Download JUnit Platform Console Standalone JAR
      run: |
        mkdir -p libs
        curl -L -o libs/junit-platform-console-standalone-1.8.2.jar https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar

    - name: Run tests
      run: java -cp "out:libs/junit-platform-console-standalone-1.8.2.jar" org.junit.platform.console.ConsoleLauncher --scan-classpath

    - name: Notify Slack on Success
      if: success() # 이 step은 job이 성공한 경우에만 실행된다.
      id: slack-success
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "channel": "#cicd-테스트",
            "attachments": [
              {
                "color": "#36a64f", # 성공시 연두색
                "title": "${{ github.repository }}", # 제목은 깃헙 레포지토리
                "title_link": "https://github.com/${{github.repository}}", # 제목 클릭시 레포지토리로 이동
                "text": "GitHub Action 성공",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "Tag",
                    "value": "${{ github.ref_name }}",
                    "short": true
                  }
                ]      
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

    - name: Notify Slack on Failure
      if: failure() # 이 step은 job이 실패한 경우에만 실행됩니다.
      id: slack-failure
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "channel": "#cicd-테스트",
            "attachments": [
              {
                "color": "#ff0000", # 실패시 빨간색
                "title": "${{ github.repository }}", # 제목은 깃헙 레포지토리
                "title_link": "https://github.com/${{github.repository}}", # 제목 클릭시 레포지토리로 이동
                "text": "GitHub Action 실패 :x:",
                "fields": [
                  {
                    "title": "Repository",
                "value": "${{ github.repository }}",
                "short": true
                  },
                  {
                    "title": "Tag",
                    "value": "${{ github.ref_name }}",
                    "short": true
                  }
                ]      
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
